services:
  server:
    image: node:25-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app:z
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development

    command: sh -c "npm install && npx prisma db pull && npx prisma generate && npm run dev"

  client:
    image: node:25-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app:z
      - /app/node_modules
    environment:
      - VITE_API_TARGET=http://server:3000
    depends_on:
      - server
    command: sh -c "npm install && npm run dev -- --host"

  bot:
    image: python:3.12-slim
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./bot:/app:z
      - /app/.venv
      - bot-model:/app/model
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: sh -c "pip install uv && uv sync && uv run src/setup.py && uv run uvicorn src.main:app --host 0.0.0.0 --port 8000"


volumes:
  bot-model:
